USE [master]
GO

/*Creating Database Application*/
CREATE DATABASE [DB_ENGAGE_DEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_ENGAGE_DEV', FILENAME = N'D:\rdsdbdata\DATA\DB_ENGAGE_DEV.mdf' , SIZE = 1048576KB , MAXSIZE = 2097152KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DB_ENGAGE_DEV_log', FILENAME = N'D:\rdsdbdata\DATA\DB_ENGAGE_DEV_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ENGAGE_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET  MULTI_USER 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_ENGAGE_DEV] SET  READ_WRITE 
GO


